var contrib_data = [
    {
        "age": "1 day",
        "commit_msg": "Change '?' to '<module>' in some doc examples. Patch by Mariatta Wijaya.",
        "committer": "terryjreedy",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 0,
        "issue_id": "28315",
        "repo_name": "cpython",
        "start": "2016-09-30"
    },
    {
        "age": "1 day",
        "commit_msg": "Fix typo in asyncio.Task() documentation. Patch by Mariatta Wijaya.",
        "committer": "berkerpeksag",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 1,
        "issue_id": "28348",
        "repo_name": "cpython",
        "start": "2016-10-04"
    },
    {
        "age": "7 days",
        "commit_msg": "Show how to change log level for asyncio.",
        "committer": "gvanrossum",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 2,
        "issue_id": "21443",
        "repo_name": "cpython",
        "start": "2016-10-13"
    },
    {
        "age": "9 days",
        "commit_msg": "Document unittest.TestCase.longMessage. (Mariatta)",
        "committer": "gvanrossum",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 3,
        "issue_id": "26869",
        "repo_name": "cpython",
        "start": "2016-10-13"
    },
    {
        "age": "7 days",
        "commit_msg": "Update XML vulnerability table to use Safe/Vulnerable instead of No/Yes.",
        "committer": "gvanrossum",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 4,
        "issue_id": "18789",
        "repo_name": "cpython",
        "start": "2016-10-13"
    },
    {
        "commit_msg": "Clarify example of overriding the convert_arg_line_to_args method. Patch by Mariatta Wijaya.",
        "committer": "berkerperksag",
        "cpython_type": true,
        "group": 0,
        "id": 5,
        "issue_id": "28455",
        "repo_name": "cpython",
        "start": "2016-10-16"
    },
    {
        "age": "1 day",
        "commit_msg": "Optimize csv.DictWriter for large number of columns. Patch by Mariatta Wijaya.",
        "committer": "methane",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 6,
        "issue_id": "18219",
        "repo_name": "cpython",
        "start": "2016-10-21"
    },
    {
        "age": "1 day",
        "commit_msg": "Deprecate asyncore/asynchat. Patch by Mariatta.",
        "committer": "gvanrossum",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 7,
        "issue_id": "25002",
        "repo_name": "cpython",
        "start": "2016-10-25"
    },
    {
        "age": "21 days",
        "commit_msg": "Update OS X installers to use SQLite 3.14.2. Patch by Mariatta Wijaya.",
        "committer": "ned-deily",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 8,
        "issue_id": "28208",
        "repo_name": "cpython",
        "start": "2016-10-31"
    },
    {
        "age": "21 days",
        "commit_msg": "Update macOS installer build to use OpenSSL 1.0.2j. Original patch by Mariatta Wijaya.",
        "committer": "ned-deily",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 9,
        "issue_id": "28248",
        "repo_name": "cpython",
        "start": "2016-10-31"
    },
    {
        "age": "1 day",
        "commit_msg": "Improve docs for create_unix_connection(). By Mariatta.",
        "committer": "gvanrossum",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 10,
        "issue_id": "26980",
        "repo_name": "cpython",
        "start": "2016-11-03"
    },
    {
        "age": "34 days",
        "commit_msg": "Document Transport.set_protocol and get_protocol",
        "committer": "methane",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 11,
        "issue_id": "28088",
        "repo_name": "cpython",
        "start": "2016-11-04"
    },
    {
        "commit_msg": "Convert PEP 202 to reST",
        "committer": "gvanrossum",
        "cpython_type": false,
        "group": 3,
        "id": 12,
        "issue_id": "121",
        "repo_name": "peps",
        "start": "2016-10-23"
    },
    {
        "commit_msg": "Made \"install dependencies\" as Step number one",
        "committer": "ncoghlan",
        "cpython_type": false,
        "group": 2,
        "id": 13,
        "issue_id": "37",
        "repo_name": "devguide",
        "start": "2016-09-20"
    },
    {
        "commit_msg": "use bold font for h1",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 14,
        "issue_id": "1022",
        "repo_name": "pythondotorg",
        "start": "2016-09-27"
    },
    {
        "commit_msg": "Add styling to admonitions",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 15,
        "issue_id": "1020",
        "repo_name": "pythondotorg",
        "start": "2016-09-27"
    },
    {
        "commit_msg": "Improve documentation for generating PEP pages",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 16,
        "issue_id": "1015",
        "repo_name": "pythondotorg",
        "start": "2016-09-22"
    },
    {
        "commit_msg": "Remove lengthy text in job info box",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 17,
        "issue_id": "1012",
        "repo_name": "pythondotorg",
        "start": "2016-09-16"
    },
    {
        "commit_msg": "Link the latest news in about page to blog.python.org",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 18,
        "issue_id": "1005",
        "repo_name": "pythondotorg",
        "start": "2016-09-11"
    },
    {
        "commit_msg": "Redirect /blog/ to /blogs/",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 19,
        "issue_id": "1006",
        "repo_name": "pythondotorg",
        "start": "2016-09-11"
    },
    {
        "commit_msg": "add sqlparse<0.2",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 20,
        "issue_id": "990",
        "repo_name": "pythondotorg",
        "start": "2016-08-13"
    },
    {
        "age": "2 days",
        "commit_msg": "Backport imaginary/complex number text from 3.x. Patch by Mariatta Wijaya.",
        "committer": "terryjreedy",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 21,
        "issue_id": "28615",
        "repo_name": "cpython",
        "start": "2016-11-11"
    },
    {
        "age": "2 days",
        "commit_msg": "The subprocess.Popen.wait method's undocumented endtime parameter now raises a DeprecationWarning. It was deprecated in 3.4. It was never documented prior to that.",
        "committer": "gpshead",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 22,
        "issue_id": "20572",
        "repo_name": "cpython",
        "start": "2016-11-20"
    },
    {
        "age": "19 days",
        "commit_msg": "list.index documentation missing start and stop arguments. (Contributed by Mariatta Wijaya.)",
        "committer": "rhettinger",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 23,
        "issue_id": "28587",
        "repo_name": "cpython",
        "start": "2016-11-21"
    },
    {
        "age": "47 days",
        "commit_msg": "Improve for statistics data arguments. (Contributed by Mariatta Wijaya.)",
        "committer": "rhettinger",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 24,
        "issue_id": "27825",
        "repo_name": "cpython",
        "start": "2016-11-21"
    },
    {
        "age": "2 days",
        "commit_msg": "Restify PEP 3145",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 25,
        "issue_id": "143",
        "repo_name": "peps",
        "start": "2016-11-28"
    },
    {
        "age": "2 days",
        "commit_msg": "Restify PEP 303",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 26,
        "issue_id": "142",
        "repo_name": "peps",
        "start": "2016-11-28"
    },
    {
        "age": "2 days",
        "commit_msg": "Restify PEP 206",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 27,
        "issue_id": "144",
        "repo_name": "peps",
        "start": "2016-11-29"
    },
    {
        "commit_msg": "restify PEP 349",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "id": 28,
        "issue_id": "148",
        "repo_name": "peps",
        "start": "2016-12-03"
    },
    {
        "commit_msg": "Fix typos in PEP 524 and PEP 529",
        "committer": "Rosuav",
        "cpython_type": false,
        "group": 3,
        "id": 29,
        "issue_id": "150",
        "repo_name": "peps",
        "start": "2016-12-04"
    },
    {
        "commit_msg": "Typo in readme.txt",
        "committer": "Mariatta",
        "cpython_type": false,
        "group": 4,
        "id": 30,
        "issue_id": "182",
        "repo_name": "planet",
        "start": "2016-12-05"
    },
    {
        "age": "7 days",
        "commit_msg": "Document TCP_NODELAY in asyncio. Initial patch by Mariatta Wijaya.",
        "committer": "1st1",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 31,
        "issue_id": "28089",
        "repo_name": "cpython",
        "start": "2016-12-12"
    },
    {
        "commit_msg": "Add feed for Janusworx",
        "committer": "tseaver",
        "cpython_type": false,
        "group": 4,
        "id": 32,
        "issue_id": "184",
        "repo_name": "planet",
        "start": "2016-12-13"
    },
    {
        "commit_msg": "Advise using the latest stable version of Sphinx",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 2,
        "id": 33,
        "issue_id": "86",
        "repo_name": "devguide",
        "start": "2016-12-13"
    },
    {
        "commit_msg": "Installation docs: Mention Elasticsearch",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 1,
        "id": 34,
        "issue_id": "1040",
        "repo_name": "pythondotorg",
        "start": "2016-12-15"
    },
    {
        "age": "2 days",
        "commit_msg": "Remove FAQ",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 2,
        "has_age": true,
        "id": 35,
        "issue_id": "37",
        "repo_name": "devguide",
        "start": "2017-01-04"
    },
    {
        "commit_msg": "Update outdated links in PEP 3107 with archived pages",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "id": 36,
        "issue_id": "169",
        "repo_name": "peps",
        "start": "2017-01-01"
    },
    {
        "commit_msg": "Fix broken url in PEP 3107",
        "committer": "Rosuav",
        "cpython_type": false,
        "group": 3,
        "id": 37,
        "issue_id": "170",
        "repo_name": "peps",
        "start": "2017-01-01"
    },
    {
        "commit_msg": "reSTify 10 PEPs",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "id": 38,
        "issue_id": "174",
        "repo_name": "peps",
        "start": "2017-01-07"
    },
    {
        "age": "3 days",
        "commit_msg": "reSTify 10 more PEPs",
        "committer": "berkerpeksag",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 39,
        "issue_id": "175",
        "repo_name": "peps",
        "start": "2017-01-10"
    },
    {
        "commit_msg": "Another batch of 10 PEPs converted",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "id": 40,
        "issue_id": "177",
        "repo_name": "peps",
        "start": "2017-01-10"
    },
    {
        "age": "6 days",
        "commit_msg": "Convert 10 PEPs to reSt",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 41,
        "issue_id": "180",
        "repo_name": "peps",
        "start": "2017-01-19"
    },
    {
        "age": "1 day",
        "commit_msg": "Remove extra backticks",
        "committer": "brettcannon",
        "cpython_type": false,
        "group": 3,
        "has_age": true,
        "id": 42,
        "issue_id": "184",
        "repo_name": "peps",
        "start": "2017-01-19"
    },
    {
        "age": "132 days",
        "commit_msg": "Point to Wiki for Editors and Python IDEs on Unix. Patch contributed by Mariatta Wijaya.",
        "committer": "orshentil",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 43,
        "issue_id": "26149",
        "repo_name": "cpython",
        "start": "2017-01-25"
    },
    {
        "age": "3 days",
        "commit_msg": "Clarify ordering of UNIX shebang line as source encoding line",
        "committer": "Mariatta",
        "cpython_type": true,
        "group": 0,
        "has_age": true,
        "id": 44,
        "issue_id": "29381",
        "repo_name": "cpython",
        "start": "2017-02-01"
    }
];